# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += periph_timer
FEATURES_PROVIDED += periph_rtc
FEATURES_PROVIDED += periph_gpio

# Various other features (if any)

# The board MPU family (used for grouping by the CI system)
FEATURES_MCU_GROUP = msp430
